apiVersion: v1
kind: Secret
metadata:
  name: yolo-service-secret
  namespace: cam-det
  labels:
    app.kubernetes.io/name: yolo-service
    app.kubernetes.io/part-of: cam-system
type: Opaque
stringData:
  CAMERA_AUTH_JWT_SECRET: c3b4f828b50e4bf1583b8217b6b0054aeef10f08319457b8205fad39231ab121
