// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection.proto

#include "detection.pb.h"
#include "detection.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace detection {

static const char* DetectionService_method_names[] = {
  "/detection.DetectionService/StreamDetections",
};

std::unique_ptr< DetectionService::Stub> DetectionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DetectionService::Stub> stub(new DetectionService::Stub(channel, options));
  return stub;
}

DetectionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamDetections_(DetectionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::detection::Frame>* DetectionService::Stub::StreamDetectionsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::detection::Frame>::Create(channel_.get(), rpcmethod_StreamDetections_, context, request);
}

void DetectionService::Stub::async::StreamDetections(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::detection::Frame>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::detection::Frame>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamDetections_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::detection::Frame>* DetectionService::Stub::AsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::detection::Frame>::Create(channel_.get(), cq, rpcmethod_StreamDetections_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::detection::Frame>* DetectionService::Stub::PrepareAsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::detection::Frame>::Create(channel_.get(), cq, rpcmethod_StreamDetections_, context, request, false, nullptr);
}

DetectionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DetectionService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< DetectionService::Service, ::google::protobuf::Empty, ::detection::Frame>(
          [](DetectionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::detection::Frame>* writer) {
               return service->StreamDetections(ctx, req, writer);
             }, this)));
}

DetectionService::Service::~Service() {
}

::grpc::Status DetectionService::Service::StreamDetections(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::detection::Frame>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace detection
#include <grpcpp/ports_undef.inc>

