// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection.proto
#ifndef GRPC_detection_2eproto__INCLUDED
#define GRPC_detection_2eproto__INCLUDED

#include "detection.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace detection {

class DetectionService final {
 public:
  static constexpr char const* service_full_name() {
    return "detection.DetectionService";
  }

  class StubInterface {
   public:
    virtual ~StubInterface() {}

    std::unique_ptr<::grpc::ClientReaderInterface<::detection::Frame>> StreamLiveFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr<::grpc::ClientReaderInterface<::detection::Frame>>(
          StreamLiveFramesRaw(context, request));
    }
    std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>> AsyncStreamLiveFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>>(
          AsyncStreamLiveFramesRaw(context, request, cq, tag));
    }
    std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>> PrepareAsyncStreamLiveFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>>(
          PrepareAsyncStreamLiveFramesRaw(context, request, cq));
    }

    std::unique_ptr<::grpc::ClientReaderInterface<::detection::Frame>> StreamDetectionFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr<::grpc::ClientReaderInterface<::detection::Frame>>(
          StreamDetectionFramesRaw(context, request));
    }
    std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>> AsyncStreamDetectionFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>>(
          AsyncStreamDetectionFramesRaw(context, request, cq, tag));
    }
    std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>> PrepareAsyncStreamDetectionFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<::grpc::ClientAsyncReaderInterface<::detection::Frame>>(
          PrepareAsyncStreamDetectionFramesRaw(context, request, cq));
    }

    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamLiveFrames(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                                    ::grpc::ClientReadReactor<::detection::Frame>* reactor) = 0;
      virtual void StreamDetectionFrames(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                                         ::grpc::ClientReadReactor<::detection::Frame>* reactor) = 0;
    };

    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }

   private:
    virtual ::grpc::ClientReaderInterface<::detection::Frame>* StreamLiveFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface<::detection::Frame>* AsyncStreamLiveFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface<::detection::Frame>* PrepareAsyncStreamLiveFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) = 0;

    virtual ::grpc::ClientReaderInterface<::detection::Frame>* StreamDetectionFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface<::detection::Frame>* AsyncStreamDetectionFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface<::detection::Frame>* PrepareAsyncStreamDetectionFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) = 0;
  };

  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr<::grpc::ChannelInterface>& channel,
         const ::grpc::StubOptions& options = ::grpc::StubOptions());

    std::unique_ptr<::grpc::ClientReader<::detection::Frame>> StreamLiveFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr<::grpc::ClientReader<::detection::Frame>>(
          StreamLiveFramesRaw(context, request));
    }
    std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>> AsyncStreamLiveFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>>(
          AsyncStreamLiveFramesRaw(context, request, cq, tag));
    }
    std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>> PrepareAsyncStreamLiveFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>>(
          PrepareAsyncStreamLiveFramesRaw(context, request, cq));
    }

    std::unique_ptr<::grpc::ClientReader<::detection::Frame>> StreamDetectionFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
      return std::unique_ptr<::grpc::ClientReader<::detection::Frame>>(
          StreamDetectionFramesRaw(context, request));
    }
    std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>> AsyncStreamDetectionFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>>(
          AsyncStreamDetectionFramesRaw(context, request, cq, tag));
    }
    std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>> PrepareAsyncStreamDetectionFrames(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<::grpc::ClientAsyncReader<::detection::Frame>>(
          PrepareAsyncStreamDetectionFramesRaw(context, request, cq));
    }

    class async final : public StubInterface::async_interface {
     public:
      void StreamLiveFrames(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                            ::grpc::ClientReadReactor<::detection::Frame>* reactor) override;
      void StreamDetectionFrames(::grpc::ClientContext* context, const ::google::protobuf::Empty* request,
                                 ::grpc::ClientReadReactor<::detection::Frame>* reactor) override;

     private:
      friend class Stub;
      explicit async(Stub* stub) : stub_(stub) {}
      Stub* stub_;
    };

    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr<::grpc::ChannelInterface> channel_;
    class async async_stub_{this};

    ::grpc::ClientReader<::detection::Frame>* StreamLiveFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) override;
    ::grpc::ClientAsyncReader<::detection::Frame>* AsyncStreamLiveFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader<::detection::Frame>* PrepareAsyncStreamLiveFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) override;

    ::grpc::ClientReader<::detection::Frame>* StreamDetectionFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request) override;
    ::grpc::ClientAsyncReader<::detection::Frame>* AsyncStreamDetectionFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader<::detection::Frame>* PrepareAsyncStreamDetectionFramesRaw(
        ::grpc::ClientContext* context, const ::google::protobuf::Empty& request,
        ::grpc::CompletionQueue* cq) override;

    const ::grpc::internal::RpcMethod rpcmethod_StreamLiveFrames_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamDetectionFrames_;
  };

  static std::unique_ptr<Stub> NewStub(
      const std::shared_ptr<::grpc::ChannelInterface>& channel,
      const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();

    virtual ::grpc::Status StreamLiveFrames(::grpc::ServerContext* context,
                                            const ::google::protobuf::Empty* request,
                                            ::grpc::ServerWriter<::detection::Frame>* writer);
    virtual ::grpc::Status StreamDetectionFrames(::grpc::ServerContext* context,
                                                 const ::google::protobuf::Empty* request,
                                                 ::grpc::ServerWriter<::detection::Frame>* writer);
  };
};

}  // namespace detection

#include <grpcpp/ports_undef.inc>

#endif  // GRPC_detection_2eproto__INCLUDED
